server {
    # port 443 en SSL/TLS ONLY !
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name mlaffita.42.fr; # check si ok comme ca ou si local host ?

    # Certificats SSL générés dans le Dockerfile
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Protocoles TLS imposés par le sujet
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/html;
    index index.html index.php;

    location / {
        try_files $uri $uri/ =404;
    }

	# ici a la fin on mettra des autres trucs 
	# on va transmettre les fichier php a wordpress sur le port 9000
	# a faire plus tard 
}