server {
    # port 443 en SSL/TLS ONLY !
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name mlaffita.42.fr;

    # Certificats SSL générés dans le Dockerfile
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Protocoles TLS imposés par le sujet
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/html;
    index index.html index.php;

    location / {
        try_files $uri $uri/ =404;
    }

	# ici a la fin on mettra des autres trucs 
	# on va transmettre les fichier php a wordpress sur le port 9000
	# a faire plus tard 
}

# On ouvre un bloc de config de serveur
# listen dit a Nginx d'ecouter les connexions chifrees sur le port 443
# [::] est la représentation littérale de l'adresse IP de boucle locale en IPv6 
# (équivalent d'un wildcard 0.0.0.0 en IPv4)
# pour la location, on check si le fichier existe, sinon dossier, et si rien erreur 