server {
    # port 443 en SSL/TLS ONLY !
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name mlaffita.42.fr;

    # Certificats SSL générés dans le Dockerfile
    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Protocoles TLS imposés par le sujet
    ssl_protocols TLSv1.2 TLSv1.3;

    root /var/www/html;
    index index.html index.php;

    location / {
        try_files $uri $uri/ =404;
    }

	# Redirection du code PHP vers le conteneur WordPress (Port 9000)
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass wordpress:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}

# On ouvre un bloc de config de serveur
# listen dit a Nginx d'ecouter les connexions chifrees sur le port 443
# [::] est la représentation littérale de l'adresse IP de boucle locale en IPv6 
# (équivalent d'un wildcard 0.0.0.0 en IPv4)
# pour la location, on check si le fichier existe, sinon dossier, et si rien erreur 

# ^(.+\.php)(/.+)$ = decoupe en 2 variables nginx 
# 1- le chemin vers le fichier script php 
# 2- parametre de chemin supplementaire 
# securite pour eviter vulnerabilite 

# fastcgi_pass wordpress:9000; = pont reseau
# va transmettre la requete fastCGI au service distant nommmé wordpress sur le port 9000
# le nom d'hôte wordpress sera automatiquement résolu vers l'adresse IP du conteneur WordPress

# index pour quel fichier par defaut utiliser 
# fastcgi_param est le fichier de config fourni par debian 
# toutes les variables d'environnement HTTP standardisées 
# (comme REQUEST_METHOD, QUERY_STRING, CONTENT_TYPE, etc.) dont PHP a besoin
# pour comprendre la requête du client.
# la derniere ligne est pour le chemin physique du fichier script PHP à exécuter
# en utilisant la variable $document_root (la racine configurée dans NGINX (/var/www/html)) 
# et $fastcgi_script_name (le chemin du script PHP demandé).