# 3.8 est la norme stable pour docker
version: '3.8'

# Bloc services va lister tous les conteneurs 
services:

  # Data base MariaDB
  mariadb:
    # build va construire image localement a partir des fichiers sources (avec chemin du doss + dockerfile)
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    # Si le service plante ou si la machine redémarre, Docker relancera automatiquement le conteneur
    restart: always
    env_file:
      - ../.env
    # Associe le volume nommé db_data au dossier /var/lib/mysql à l'intérieur du conteneur (là où MariaDB stocke physiquement les tables SQL).
    volumes:
      - db_data:/var/lib/mysql
    # Va connecter le conteneur au reseau prive 
    networks:
      - inception_network

  # website WordPress
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: always
    # etabli un ordre : Docker lancera le conteneur mariadb avant de démarrer wordpress
    depends_on:
      - mariadb
    env_file:
      - ../.env
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception_network

  # web server NGINX
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    # ordre ici aussi : NGINX attend que le conteneur wordpress soit démarré avant de se lancer
    depends_on:
      - wordpress
    # Le seul point d entree !!! (check diagram sujet)
    ports:
      - "443:443"
    # NGINX monte le même volume wp_data que WordPress
    # cela permet à NGINX de lire directement les fichiers statiques (.css, .js, images) dans /var/www/html sans repasser par PHP.
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception_network

# volumes en bindmount x 2
volumes:
  wp_data:
    name: wp_data
  db_data:
    name: db_data

# reseau virtuel de type bridge 
networks:
  inception_network:
    driver: bridge

# description de l'infrastructure ici
# version: '3.8'
# services: 
# et la on met nginx
# mariadb
# ...
# volume
# network
# secrets ??

# COMMENT CA MARCHE
# ce fichier va servir de chef d'orchestre pour lancer les conteneurs
# pour nginx, va lire le dockerfile qui est ds le doss ... et construit le 
# pour mariadb, la lire ds requirement/maria .... 
# pour wordpress, pareil, lire le dockerfile ds requirement/wordpress
# 
# donc docker va lancer 3 build, creer 3 images, et ensuite lancer 3 conteneurs
# sur le meme reseau 
#
# Preciser que NGINX dépend de WordPress et que WordPress dépend de MariaDB:
# services:
# 	nginx:
#     	depends_on:
#       		- wordpress
# Il faut preciser aussi quel env utilisert ( meme si c'est le meme env pout tout les srvices )

# RESEAU BRIDGE
# mode bridge va creer un switch virtuel au sein de docker. Tts les conteneurs branches sur ce reseau vont recevoir adresse IP privee
# Sur un réseau Bridge personnalisé, Docker intègre un serveur DNS interne
# donc chaque conteneur peut joindre un autre conteneur en utilisant le nom du service comme nom d'hôte
# ( defini ds le docker compose ) 
# NGINX communique avec WordPress via wordpress:9000 
# WordPress communique avec MariaDB via mariadb:3306

# seul NGINX est exposé sur le port 443 de l'ordi
# maria db et wordpress ne sont pas exposés sur l'ordi hote, donc pas accessibles depuis l'exterieur
# communiquent uniquement a l'interieur du reseau bridge inception-network

# VOLUMES BIND MOUNT
# ATTENTION PAS AUTORISÉ DONC MODIF ( mais pour info qd meme)
# De base un conteneur est ephemere. Si on le docker rm, tt ce qui est ecrit sur le disc virtuel disparait
# Ms bindmount va creer une passerelle entre un doss de l'ordi hote et un doss du conteneur 
# permet la persistance des données. Donc si on supprime le conteneur, les données restent sur l'ordi hote
