[www]
user = www-data
group = www-data
listen = 0.0.0.0:9000
listen.owner = www-data
listen.group = www-data

pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
;
; indique d'abord les proprietaires des processus
; quel utilisateur et quel group vont excecuter le code PHP
; ne doit jamais s executer en tant que root (securite)
;
; utilisateur standard www-data (créé par défaut sur Debian pour les services web)
; ecoute sur toutes les connexions entrantes sur le réseau via le port 9000 
; sur toutes les interfaces réseau (0.0.0.0)
; c'est garce a ca que NGINX va envoyer ses requetes fastCGI vers wordpress
;
; listen owner et groupe : permission 
; PM = process manager. Dynamic = le nombre de processus PHP-FPM est ajusté dynamiquement en fonction de la charge du serveur.
; On set up le nombre maximum de child qui tournent en meme temps 
; au debut du lancement du conteneur on cree d'office 2 processus 
; Reserve minimal de 1 ( si moins de 1 inactif php va creer un nouveau )
; Reserve maximal de 3 ( si plus de 3 inactif php va tuer un processus )
;
; NGINX et Wordpress sont ds 2 conteneurs separes donc ne peuvent communiquer via socket local
; on doit forcer php a ecouter sur le port 9000 de toutes les interfaces reseau
; NGINX va transmettre les requetes php a travers le reseau docker 