# la version 
FROM debian:bookworm

# installation des logiciels et dependance
RUN apt-get update && apt-get install -y
	# nginx ?
	# mariadb ?
	# wordpress ? 

COPY 
# mettre config et copie des fichiers ?

RUN
# droit d execution, environnement, etc

ENTRYPOINT
# commande au lancement du container



# le docker de maria db va creer la base de donnée
# doit contenir l'install de mariadb server, la config pour ouvrir le bon port
# et script pour creer utilistauers de la base de données
