FROM debian:bookworm

RUN 

COPY

ENTRYPOINT

CMD

# faire tourner le code php de wordrpress
# contient instal de php-fpm, les extensions php
# l'outil wp-cli pour ddl et installer wordpress ( port 9000)