[mysqld]
user                    = mysql
port                    = 3306
bind-address            = 0.0.0.0
datadir                 = /var/lib/mysql

# parametre indispensables sont :
# user, port, bind-address, datadir
# qui excecute le srveur, sur quel port, sur quelle interface, et ou on stock les donnees

# 0.0.0.0 car comme wordpress est ds un autre conteneur, 
# il faut que mariadb ecoute sur toutes les interfaces pour autoriser la connexion
# doit ecouter sur le port 3306 pour autoriser connexino wordpress 
# 3306 est le port par defaut, mais ici on rend la config explicite 
